### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [channeladvisor/channeladvisor-wtb-gtm-template#5]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "requestInformation" and "accessToken" when generating the url
var url = 'https://strack.where-to-buy.co/api/v1/gtm/recordSale/' + requestInformation + "&s.at="+accessToken;

**Comment by ezequielolivera** [comment]
Hi,

We just made the changes. Could you please review now.

Thanks in advance.

**Comment by ezequielolivera** [comment]
> Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.
> 
> 1. encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "requestInformation" and "accessToken" when generating the url
>    var url = 'https://strack.where-to-buy.co/api/v1/gtm/recordSale/' + requestInformation + "&s.at="+accessToken;
